# Generated by Django 4.2.4 on 2023-08-18 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooom',
            name='name',
        ),
    ]
