# Generated by Django 4.2.4 on 2023-08-18 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_rooom_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rooom',
        ),
    ]
